language: node_js

node_js:
  - "12.16.3"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - yarn lint
  - yarn jest --coverage
